### ISSUE TITLE
Test-ServiceExists failes on Sandbox - Get-WmiObject : Provider load failure 

### ISSUE THREAD

**Issue by AlkHacNar** [PSAppDeployToolkit/PSAppDeployToolkit#1031]
### Prerequisites

- [X] Ensure you write a short, descriptive title after [Bug] above.
- [X] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [X] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

3.10.1

### Describe the bug

I tryed to get the Show-InstallationWelcome command to work with the serviceui. on a test notebook it worked fine, but it failed in the Windows Sandbox, cause it couldn't check for the service
`[Initialization] :: Failed check to see if service [Schedule] exists.`
I found out, that the Test-ServiceExists didn't work properly, first because of the `$env:ComputerName`, which is no promlem to fix int he sandbox with `$(hostname)`. But then it still didn't run with the failure `Get-WmiObject : Provider load failure `.
I don't know if there are more functions, which aren't working as expected in the sandbox and I know that psadt isn't really build to run in the sandbox, but I'd just wanted you to know. Maybe there is a fix/ workaround for the sandbox for this?

### Steps to reproduce

1.Show-InstallationWelcome
2.Test-ServiceExists

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 22H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : de-DE
OsMuiLanguages       : {de-DE, cs-CZ, en-GB, en-US...}
KeyboardLayout       : en-US
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Mobile
```

**Comment by mjr4077au** [comment]
This has already been addressed in v4.0 but can't be addressed here as we need to use the legacy WMI cmdlets for backwards compatibility.

**Comment by AlkHacNar** [comment]
All fine, maybe MS will fix it in the sandbox itself. I still don't get why it don't have the Provider of the  Win32_Service Class.

**Comment by mjr4077au** [comment]
I doubt its missing that CIM class, it's more that the WMI cmdlets have been deprecated for years. Get-CimInstance should work fine

**Comment by AlkHacNar** [comment]
Nope, get the same error
`PS C:\Users\WDAGUtilityAccount\Desktop\PSADT> Get-CimInstance -Class Win32_Service
Get-CimInstance : Provider load failure 
At line:1 char:1
+ Get-CimInstance -Class Win32_Service
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (root\cimv2:Win32_Service:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041013,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand`

**Comment by mjr4077au** [comment]
Then I'd say this is still unresolved in v4.0 and I'll have to do more investigation! You know what they say about assumptions, looks like I assumed wrong here about the issue.

**Comment by mjr4077au** [comment]
@AlkHacNar, I've been testing on Windows Sandbox and can replicate the fault. This issue doesn't appear repairable without breaking the API that callers are expecting to receive from the function. We'll address this for v4.0 though.

**Comment by AlkHacNar** [comment]
All good, it's just I try to test in the sandbox sometimes and just found it and wanted to tell you guys. Like I said, psadt wasn't created for sandbox and it's MSs fault that the sandbox isn't "complete"^^, but it would be great if it works there as well, if possible,  be it in v4 or v5 ;-)
