### ISSUE TITLE
[Bug] Triggering SCCM HardwareInventory fails

### ISSUE THREAD

**Issue by lkb-wrk** [PSAppDeployToolkit/PSAppDeployToolkit#1560]
### Prerequisites

- [x] Ensure you write a short, descriptive title after [Bug] above.
- [x] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [x] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.1.0

### Describe the bug

Using [4.1.0 dev](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/16516489515)  I have a problem triggering the SCCM Client Actions like HardwareInventory.

> [Post-Install] :: Failed to trigger SCCM Schedule Task ID [HardwareInventory]. Fehler beim Aufrufen der Methode, da [System.Object[]] keine Methode mit dem Namen "op_RightShift" enthält.

<img width="1117" height="216" alt="Image" src="https://github.com/user-attachments/assets/041ed77c-9d23-4e13-948f-2b90e9b3f21b" />

[DE_WRK_APP_VMWare_VMware-Tools_x64_12.5.3.52671_F10002_P11809_B001_PSAppDeployToolkit_Install.log](https://github.com/user-attachments/files/21441045/DE_WRK_APP_VMWare_VMware-Tools_x64_12.5.3.52671_F10002_P11809_B001_PSAppDeployToolkit_Install.log)

### Steps to reproduce

1. Install Module or Create Package with current dev build
2. Add `Invoke-ADTSCCMTask -ScheduleId HardwareInventory`
3. Run elevated

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 23H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 22621.1.amd64fre.ni_release.220506-1250
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Desktop


global.json file:
  Not found

Host:
  Version:      6.0.21
  Architecture: x64
  Commit:       e40b3abf1b

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by mjr4077au** [comment]
Thanks for the report! This has been addressed via https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/e4fe5c6b0f938013714ad39eaee8bab242433119. A new build will be available here in ~15 minutes for testing: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/16535574634.

**Comment by lkb-wrk** [comment]
Thank you for the fast response as always. The error message changed, but it still fails:

<img width="1107" height="326" alt="Image" src="https://github.com/user-attachments/assets/fe74f428-42dd-45b1-8942-5b458445c617" />

**Comment by mjr4077au** [comment]
I've just headed to bed but I'll take a look at this in the morning. Do you know if the trigger worked despite the error?

**Comment by lkb-wrk** [comment]
All good, I've noticed we are on oposite sides of the globe 🌎 

No, the schedule is not triggered.

Looking at the code of Invoke-ADTSCCMTask and trying to recreate how you transform the string "HardwareInventory" to the needed GUID for the trigger, but can't get it to work either:

<img width="1707" height="256" alt="Image" src="https://github.com/user-attachments/assets/7e348b98-003c-413e-90d3-447d4b7630c2" />

**Comment by mjr4077au** [comment]
The challenging part for me here is I don't have access to a ConfigMgr environment to test this directly, so I can only go off the specifications.

Can you please run `Invoke-CimMethod -Namespace ROOT\CCM -ClassName SMS_Client -MethodName TriggerSchedule -Arguments @{ sScheduleID = '{00000000-0000-0000-0000-000000000001}' }` directly and show me the full output you receive in the console?

The cmdlet `Invoke-CimMethod` is meant to return an object with a ReturnValue property. This is meant to be 0 on success, or another value upon failure. However based on your error, the ReturnValue property is null which makes no sense.

**Comment by mjr4077au** [comment]
> Looking at the code of Invoke-ADTSCCMTask and trying to recreate how you transform the string "HardwareInventory" to the needed GUID for the trigger, but can't get it to work either:

Try this out, it'll work better:
```powershell
PS D:\Repos\PSAppDeployToolkit\src> $ScheduleId = [PSADT.ConfigMgr.TriggerScheduleId]::HardwareInventory
PS D:\Repos\PSAppDeployToolkit\src> @{ sScheduleID = [System.Guid]::new([System.Byte[]](0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (([System.Int32]$ScheduleId -band 0xFF00) -shr 8), ([System.Int32]$ScheduleId -band 0xFF))).ToString('b') }

Name                           Value
----                           -----
sScheduleID                    {00000000-0000-0000-0000-000000000001}


PS D:\Repos\PSAppDeployToolkit\src>
```
The GUID ending in 1 is exactly as it's documented on Microsoft's website: https://learn.microsoft.com/en-us/intune/configmgr/develop/reference/core/clients/client-classes/triggerschedule-method-in-class-sms_client#parameters

**Comment by lkb-wrk** [comment]
Yeah it seems to be empty.
But the Schedule does trigger.

<img width="1036" height="197" alt="Image" src="https://github.com/user-attachments/assets/ce198633-41a2-4c38-9f6e-ba6c380de42d" />


And sorry I need to revise my statement that ADT doesnt trigger the schedule.
`Invoke-ADTSCCMTask -ScheduleID HardwareInventory` DOES trigger the schedule despite the error:

<img width="2574" height="977" alt="Image" src="https://github.com/user-attachments/assets/548e5b00-d8e6-40b3-b1f4-7209f3dc8bfe" />

**Comment by mjr4077au** [comment]
I love how Microsoft has lied to us all 😅: https://learn.microsoft.com/en-us/intune/configmgr/develop/reference/core/clients/client-classes/triggerschedule-method-in-class-sms_client#return-values

Should be truly patched via https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/bf0646fd5f9bcf1521aac057d3bce9974f22e6bc. Try [this build](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/16551231087) out in ~15 minutes or so.

**Comment by lkb-wrk** [comment]
Thank you as always 💪

Can confirm, error is gone:

<img width="2030" height="808" alt="Image" src="https://github.com/user-attachments/assets/b4212879-ebae-4d04-a34f-06abd7a09604" />
