### ISSUE TITLE
[Bug] changes on config.psd1 causes error

### ISSUE THREAD

**Issue by cyborgrd** [PSAppDeployToolkit/PSAppDeployToolkit#1637]
### PSAppDeployToolkit version

4.1.0

### Describe the bug

When i try do a change on config.psd1, this cause an error:

Open-ADTSession : Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.
In C:\Work\Git\Wrapper\Testing\Invoke-AppDeployToolkit.ps1:365 Zeichen:19
+     $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Open-ADTSession], OutOfMemoryException
    + FullyQualifiedErrorId : System.OutOfMemoryException,Open-ADTSession

I changed only path for log file

LogPath = '$envSystemDrive\ITService\Logs\PowerShell':

 
 

### Steps to reproduce

1. change the config.psd
2. run installation

### Environment data

```console
OsName               : Microsoft Windows 11 Enterprise
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-Bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Enterprise
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US, de-DE}
KeyboardLayout       : de-DE
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rom, Stockholm, Wien
HyperVisorPresent    : True
CsPartOfDomain       : True
CsPCSystemType       : Mobile

.NET SDK:
 Version:           9.0.302
 Commit:            bb2550b9af
 Workload version:  9.0.300-manifests.183aaee6
 MSBuild version:   17.14.13+65391c53b

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.26100
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.302\

Installierte .NET-Workloads:
Es sind keine installierten Workloads zum Anzeigen vorhanden.
Konfiguriert für die Verwendung loose manifests beim Installieren neuer Manifeste.

Host:
  Version:      9.0.7
  Architecture: x64
  Commit:       3c298d9f00

.NET SDKs installed:
  8.0.413 [C:\Program Files\dotnet\sdk]
  9.0.205 [C:\Program Files\dotnet\sdk]
  9.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by cyborgrd** [comment]
As example, only changed : 

<img width="642" height="71" alt="Image" src="https://github.com/user-attachments/assets/49ba4738-7ba8-4466-8b3c-637056e995e9" />

Result:

<img width="944" height="159" alt="Image" src="https://github.com/user-attachments/assets/0a481e96-b450-47b1-a262-d5b5bdaa5db1" />

**Comment by cyborgrd** [comment]
revert back to original:

<img width="545" height="70" alt="Image" src="https://github.com/user-attachments/assets/c364b1c9-0d34-4b42-8a52-5b6cae30d14a" />

working well

<img width="1762" height="95" alt="Image" src="https://github.com/user-attachments/assets/deef478e-f8c6-4693-a449-d8921e402f8e" />

**Comment by DanGough** [comment]
Just to clarify - are you modding the config.psd1 in the config subfolder of the deployment template, and not the signed one that's contained within the PSAppDeployToolkit\config folder?

I would expect an error when modifying the latter, but not an out of memory error!

**Comment by mjr4077au** [comment]
After you've made the change and receive the OutOfMemoryExcrption, can you please run `Resolve-ADTErrorRecord -ErrorRecord $Error[0]` and provide the output here?

**Comment by DanGough** [comment]
Working for me in 4.1.0:

<img width="757" height="263" alt="Image" src="https://github.com/user-attachments/assets/775bad07-b5f2-4534-a3b4-4f2f2711b7a8" />

**Comment by mjr4077au** [comment]
Yup, we'll definitely need that resolved exception so we can see what's going on.

**Comment by cyborgrd** [comment]
i change the config.psd1 within the module folder, but i sign it with our trusted cert after changes. In previous versions up to RC3 there wasnt a problem with it. The Error after Resolve-ADTErrorRecord -ErrorRecord $Error[0]


Message               : Eine Ausnahme vom Typ "System.OutOfMemoryException" wurde ausgelöst.
                        
FullyQualifiedErrorId : System.OutOfMemoryException,Microsoft.PowerShell.Commands.OutLineOutputCommand
ScriptStackTrace      : bei Resolve-ADTErrorRecord<Process>, C:\Program Files\WindowsPowerShell\Modules\PSAppDeployToolkit\PSAppDeployToolkit.psm1: Zeile 14506
                        bei Invoke-ADTFunctionErrorHandler, C:\Program Files\WindowsPowerShell\Modules\PSAppDeployToolkit\PSAppDeployToolkit.psm1: Zeile 10153
                        bei Initialize-ADTModule<Process>, C:\Program Files\WindowsPowerShell\Modules\PSAppDeployToolkit\PSAppDeployToolkit.psm1: Zeile 9265
                        bei Open-ADTSession<Process>, C:\Program Files\WindowsPowerShell\Modules\PSAppDeployToolkit\PSAppDeployToolkit.psm1: Zeile 12537
                        bei <ScriptBlock>, C:\Work\Git\Wrapper\Testing\Invoke-AppDeployToolkit.ps1: Zeile 365
                        
PositionMessage       : In C:\Program Files\WindowsPowerShell\Modules\PSAppDeployToolkit\PSAppDeployToolkit.psm1:14506 Zeichen:21
                        + ...             $logErrorProperties.Add($propName, [PSADT.Utilities.MiscU ...
                        +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by mjr4077au** [comment]
Thanks for this, @cyborgrd. I'll get onto it shortly.

**Comment by cyborgrd** [comment]
I tested tdy also with the las 4.1.1, same problem.

**Comment by mjr4077au** [comment]
@cyborgrd could you please upload your entire config file here? Maybe rename the extension from psd1 to txt so GitHub doesn't have a sad.

**Comment by cyborgrd** [comment]
[config.psd1.txt](https://github.com/user-attachments/files/21891248/config.psd1.txt)

there you go

**Comment by mjr4077au** [comment]
I can't replicate this on your config, it's working well. Are you 100% sure you've properly updated the toolkit and aren't running an older development release? The issue you're experiencing _was_ an issue but it was resolved in development via https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/commit/de2cc1765b86245b6aa890a29b160003a1957ad2.

To keep it simple, can you please download the latest 4.1.1 template, replace _only_ the config.psd1 file, then test again? I'm 99.99% sure it'll run for you. If so, we can try to isolate it for you.

Earlier after you were doing local testing, I asked you to run `Resolve-ADTErrorRecord -ErrorRecord $Error[0]`. It might be worth running `$Error[1]; $Error[1].ScriptStackTrace` after you trigger the fault to see if we can identify it this way.

**Comment by cyborgrd** [comment]
I found the issue. The problem was that the signature wasn't trusted on the test machine. After adding the certificate to the trusted publishers, it's working now. However, the error is still very strange - it showed "OutOfMemory" instead of indicating something related to the certificate. Sorry!
