### ISSUE TITLE
[Bug] Send-ADTKeys runs into an error: Failed to send keys to window title [Setup - GUARDX] with window handle [1573902].

### ISSUE THREAD

**Issue by PHCVergouwe** [PSAppDeployToolkit/PSAppDeployToolkit#1878]
### Prerequisites

- [x] Ensure you write a short, descriptive title after [Bug] above.
- [x] Make sure to [search for any existing issues](https://github.com/psappdeploytoolkit/psappdeploytoolkit/issues) before filing a new one.
- [x] Verify you are able to reproduce the issue with the [latest released version](https://www.github.com/psappdeploytoolkit/psappdeploytoolkit/releases/latest)

### PSAppDeployToolkit version

4.1.7

### Describe the bug
```
[Install] :: Sending key(s) [N] to window title [Setup - GUARDX] with window handle [1573902].
[Install] :: Failed to send keys to window title [Setup - GUARDX] with window handle [1573902].
Error Record:
-------------
 
Message               : Exception calling "SendKeys" with "1" argument(s): "The client process returned an exception."
InnerException        : PSADT.ClientServer.ServerException: The client process returned an exception. ---> System.ComponentModel.Win32Exception: The operation completed successfully
                           at PSADT.LibraryInterfaces.User32.AttachThreadInput(UInt32 idAttach, UInt32 idAttachTo, Boolean fAttach) in D:\a\PSAppDeployToolkit\PSAppDeployToolkit\src\PSADT\PSADT\LibraryInterfaces\User32.cs:line 167
                           at PSADT.WindowManagement.WindowTools.BringWindowToFront(HWND hWnd) in D:\a\PSAppDeployToolkit\PSAppDeployToolkit\src\PSADT\PSADT\WindowManagement\WindowTools.cs:line 76
                           at PSADT.ClientServer.ClientExecutable.SendKeys(IReadOnlyDictionary`2 arguments) in D:\a\PSAppDeployToolkit\PSAppDeployToolkit\src\PSADT\PSADT.ClientServer.Client\ClientExecutable.cs:line 682
                           at PSADT.ClientServer.ClientExecutable.EnterClientServerMode(ReadOnlyDictionary`2 arguments) in D:\a\PSAppDeployToolkit\PSAppDeployToolkit\src\PSADT\PSADT.ClientServer.Client\ClientExecutable.cs:line 413
                           --- End of inner exception stack trace ---
                           at PSADT.ClientServer.ServerInstance.Invoke[T](String command) in D:\a\PSAppDeployToolkit\PSAppDeployToolkit\src\PSADT\PSADT.ClientServer.Server\ServerInstance.cs:line 622
                           at CallSite.Target(Closure , CallSite , Object , Object , Object )
 
FullyQualifiedErrorId : ServerException,Send-ADTKeys
ScriptStackTrace      : at Private:Invoke-ADTClientServerOperation, C:\_LocalData\SD_Content\Satel_GuardX_1.20.000_x86_EN_GMN_4.1.7\app\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 1365
                        at Send-ADTKeys<Process>, C:\_LocalData\SD_Content\Satel_GuardX_1.20.000_x86_EN_GMN_4.1.7\app\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 14882
                        at Install-ADTDeployment, C:\_LocalData\SD_Content\Satel_GuardX_1.20.000_x86_EN_GMN_4.1.7\app\Invoke-AppDeployToolkit.ps1: line 303
                        at <ScriptBlock>, C:\_LocalData\SD_Content\Satel_GuardX_1.20.000_x86_EN_GMN_4.1.7\app\Invoke-AppDeployToolkit.ps1: line 755
                        at <ScriptBlock>, <No file>: line 1
 
PositionMessage       : At C:\_LocalData\SD_Content\Satel_GuardX_1.20.000_x86_EN_GMN_4.1.7\app\Invoke-AppDeployToolkit.ps1:303 char:13
                        +             Send-ADTKeys -WindowTitle 'Setup - GUARDX' -Key 'N' -Wait ...
                        +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce

1.
2.
3.

### Environment data

```console
OsName               : Microsoft Windows 11 Pro
OSDisplayVersion     : 24H2
OsOperatingSystemSKU : 48
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsProductName   : Windows 10 Pro
WindowsBuildLabEx    : 26100.1.amd64fre.ge_release.240331-1435
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}
KeyboardLayout       : 00020409
TimeZone             : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
HyperVisorPresent    : True
CsPartOfDomain       : False
CsPCSystemType       : Desktop
```

**Comment by PHCVergouwe** [comment]
This did work correctly in 4.0.6

**Comment by DanGough** [comment]
Please can you explain your setup here? For example, are you at the testing stage, having launched the installer with admin rights but trying to drive the keypresses from a non-elevated terminal? I can only get that 'BringWindowToFront' error if trying to run Send-ADTKeys from a non-elevated session to interact with a window that's running elevated.

Also, this function was changed in 4.1 to run via the same client/server pathway as the user interface, so key presses effectively take place from user context, meaning they're unable to interact with processes running as another user such as system. If you wanted to run an installer interactively as system, then drive the buttons on the UI, this may no longer be possible. Since this is one of the primary uses of this function, we may need to consider reverting this or adding a switch to allow it the keypresses in system context.

When the function fails to send the keys due to this specific issue, the error is currently non-terminating, but you can add -Verbose to see more info when testing in the terminal.

**Comment by mjr4077au** [comment]
> `System.ComponentModel.Win32Exception: The operation completed successfully`

This seems to indicate a potential bug with the error handling. I'll take a look at it.

**Comment by mjr4077au** [comment]
@PHCVergouwe I've reported this issue to the [CsWin32 Team](https://github.com/microsoft/win32metadata/issues/2162) as I believe there's a metadata issue with the P/Invoke. Obviously something's going wrong still, but it'll have to sit tight for now.

**Comment by PHCVergouwe** [comment]
Hi Dan,

Sorry to not replying any sooner, but indeed I run the setup from the local system account, which would fully explain why it is not working anymore since 4.1 (and did work correctly in every 4.0.x version). Indeed it seems reverting it back to the previous way of working would be advisable 😄. Or even better: your suggestion of adding a switch.

Yours sincerely,

Paul Vergouwe
________________________________

**Comment by mjr4077au** [comment]
Hi @PHCVergouwe,

We believe this issue is already addressed for the upcoming 4.1.8 patch release, which you can see above in the previous messages.

If possible, feel free to test this 4.2.0 pre-release and let us know how it goes: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/actions/runs/20541474269.

Cheers, 
Mitch

**Comment by PHCVergouwe** [comment]
Hi Mitch,

Sorry to reply so late, but it still does not work in 4.1.8.

Cheers,

Paul
