### ISSUE TITLE
Zero Config - handle MST?

### ISSUE THREAD

**Issue by stgrdk** [PSAppDeployToolkit/PSAppDeployToolkit#73]
In AppDeployToolkitMain.ps1 line 8808 : 
"If the default Deploy-Application.ps1 hasn't been modified, check for MSI / MST and modify the install accordingly"

This line explains that MSI / MST could be handled, but it does not take MST files.
Was it omitted by purpose or was it forgotten.?

**Comment by mmashwani** [comment]
The latest 3.6.5 beta should not be able to handle MST files for zero-config MSI installations. Please test with the latest Deploy-Application.ps1 and AppDeployToolkitMain.ps1 and let me know if it's working as expected now:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/tree/master/Toolkit/AppDeployToolkit

**Comment by stgrdk** [comment]
I get this new error:

Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "An XML comment cannot contain '--', and '-' cannot be the last character. Line 54, position 5."
At C:\Users\Text\Desktop\PSAppDeployToolkit_v3.6.5\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:210 char:1
+ [Xml.XmlDocument]$xmlConfigFile = Get-Content -Path $AppDeployConfigF ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException

If i remove: 

in AppDeployToolkitConfig.xml it continues and work as expected with MST..

**Comment by mmashwani** [comment]
Thanks, that XML error should now be fixed.

**Comment by stgrdk** [comment]
Perfect.

**Comment by dersonc** [comment]
@mmashwani for the MST support, if we change the application name, version or manufacturer in the MST would the toolkit get the new values defined on the MST or it would still get the default values from the MSI?

**Comment by mmashwani** [comment]
That's a good question. It will get the values from the MSI and not from the MSP.

**Comment by mmashwani** [comment]
I would need to update the function that reads values from the MSI to add the ability to apply an MST if available and then read values. I will add it to my todo list.

**Comment by mmashwani** [comment]
@dersonc 
I created an issue for your request here:
https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/75

Please test it out and let me know if it works as expected.
