### ISSUE TITLE
Show-BalloonTip not showing when running script as another user

### ISSUE THREAD

**Issue by hockink** [PSAppDeployToolkit/PSAppDeployToolkit#741]
If you are required to run a script as an administrator or through SCCM as system, the Show-BalloonTip does not get shown.

**To Reproduce**
1. Login to a machine as a standard user
2. run your script that contains balloon tips as an administrator

**Toolkit Version:**
3.9.1

**Powershell Version:**
5.1

**Comment by PH0MB** [comment]
I also have popups because under the hood it seems to spawn a small ExecuteAsUser.vbs script which gets blocked by the recommended policy for VBScript execution:  Block JavaScript or VBScript from launching downloaded executable content
In this case I did not use the "Silent" flag for the deployment.

**Comment by cgerke** [comment]
Ditto, this execute as user function probably not a viable solution for Intune users with asr
________________________________

**Comment by t7504** [comment]
This sounds close to the issue we are experiencing, and the root cause is likely the same.  Per best practice, we block the execution of VBS file for users (but not for SCCM/SYSTEM account).  We do this with group policy by setting .VBS file extention to open in Notepad instead of Wscript.  The end result is when a user intentionally (or unintentionally) attempts to call a VBS, they receive a Windows Script Host error "There is no script engine for file extension .vbs".

Up until PSADT 3.9.0/3.9.1, there was never a problem with this setup.  Now, when running PSADT, I am getting two popups of the above "no script engine" error.  I'm not sure what changed within the PSADT code to break this, as I can see that the "Execute-ProcessAsUser" function existed prior to 3.9.0.

Unfortunately this is a showstopper for us.  We'll either need to remain on 3.8.4 or find a new packaging solution.

**Comment by t7504** [comment]
Following up, this seems to be the culprit:

## Invoke a separate PowerShell process as the current user passing the script block as a command and associated parameters to display the toast notification in the user context
            Try {                
                $executeToastAsUserScript = "$configToolkitTempPath\$($appDeployToolkitName)-ToastNotification.ps1"
                Set-Content -Path $executeToastAsUserScript -Value $toastScriptBlock -Force
                Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & `"$executeToastAsUserScript `'$BalloonTipText`' `'$BalloonTipTitle`' `'$AppDeployLogoImage`'`"; Exit `$LastExitCode }" -Wait
            }
            Catch {
            }

Did a quick test and changing "Execute-ProcessAsUser" on line 10599 to "Execute-Process" eliminates my error - but likely has other unintended consequences.....
![psadt_error](https://user-images.githubusercontent.com/13860727/215137151-a1343729-deb2-4394-85ee-c30481b92e67.jpg)

**Comment by hunterp12** [comment]
Any Execute-ProcessAsUser command creates a scheduled task that invokes a vbs script in order to not show a powershell window. Looks like they added Toast notifications for OS version 10 and newer instead of the old balloon tip style. In order for these toasts to show in the user context when run from SYSTEM/SCCM context, it needs to execute the toast as the user, thus starting the vbs script. You would probably get blocked even on 3.8.4 if you had anything trying to run in the user context from SYSTEM or SCCM install so you might never have used that. You can either turn off the balloon tips in the xml in 3.9.0 and newer, or just stick with 3.8.4. Maybe they will add a xml switch to use old balloon tips instead of the new toast so users in your situation can still get the latest updates, but bypass using the new toasts.

**Comment by t7504** [comment]
When I run PSADT 3.8.4 as a standard user (outside of SCCM) as a test I see no errors.  When I run PSADT 3.9.1 as a standard user (outside of SCCM) as a test I'm getting VBS errors as we have VBS blocked.  With 3.8.4 as a standard user, I do receive the notification messages in the lower-right corner that "installation started" and "installation completed".  With 3.9.1, I do not.  Just the errors.  If I change "show balloon tips" to FALSE in 3.9.1, the errors go away, but either way, I don't get the notification boxes I've always received up until 3.9.0.

**Comment by hunterp12** [comment]
Within the Try block on line 10598, try changing it to the below. See if that fixes it when running as a standard user. Mind you, it will still give an error when running as admin or SYSTEM context as it will use the Execute-ProcessAsUser

```
If ( -not $IsAdmin) {

    Invoke-Command -ScriptBlock $toastScriptBlock -ArgumentList $BalloonTipText, $BalloonTipTitle, $AppDeployLogoImage

} Else {

    $executeToastAsUserScript = "$configToolkitTempPath\$($appDeployToolkitName)-ToastNotification.ps1"
    Set-Content -Path $executeToastAsUserScript -Value $toastScriptBlock -Force
    Execute-ProcessAsUser -Path "$PSHOME\powershell.exe" -Parameters "-ExecutionPolicy Bypass -NoProfile -NoLogo -WindowStyle Hidden -Command & { & `"$executeToastAsUserScript `'$BalloonTipText`' `'$BalloonTipTitle`' `'$AppDeployLogoImage`'`"; Exit `$LastExitCode }" -Wait
    
}

sleep -Seconds 5         
```

**Comment by hunterp12** [comment]
On second thought.. Just go in to AppDeployToolkitConfig.xml and add UseLegacyBalloonNotifications under ShowBalloonNotifications like below:

```
<ShowBalloonNotifications>True</ShowBalloonNotifications>
<!-- [True/False] - Used to turn automatic balloon notifications on or off. -->
<UseLegacyBalloonNotifications>True</UseLegacyBalloonNotifications>
<!-- [True/False] - Used to enable Legacy balloon notifications instead of the newer toast notifications. -->
```

Then in the AppDeployToolkitMain.ps1, add the below under line 451 of configShowBallonNotifications:

`[Boolean]$configUseLegacyBalloonNotifications = [Boolean]::Parse($xmlConfigUIOptions.UseLegacyBalloonNotifications)`

and finally, change the If clause on line 10476 to:

` If ($envOSVersionMajor -lt 10 -or $configUseLegacyBalloonNotifications) {`

This should force to use the old balloon notifications used in 3.8.4.

**Comment by Skeb1ns** [comment]
Observed the behaviour and found out that balloon tips are now using the Execute-ProcessAsUser cmdlet. Just like @t7504 we also block .vbs execution by setting the default action to open vbs files with notepad.

A simple fix for the devs to overcome this is by adding `/e:vbscript` to the `$Parameters` variable:

`$Parameters = " /e:vbscript `"$executeAsUserTempPath\$($schTaskName).vbs`""`

This way wscript is explicitly told to use vbscript when running the vbs file which works for my environment (Apps deployed via Intune and using ServiceUI to allow interaction with the logged on user)

**Comment by t7504** [comment]
Thank you @Skeb1ns - that modification worked for us.  Hopefully this gets addressed permanently in an upcoming release.

**Comment by seanlillis** [comment]
Fix is available in the master branch, please let us know if this fixes both issues.

- Resolved an issue where Show-BalloonTip would not work as a standard user. (#741)
- Resolved an issue where Execute-ProcessAsUser fails due to an unexpected VBS file association. (#741)

**Comment by t7504** [comment]
Working for me.  Thank you.

**Comment by seanlillis** [comment]
> Working for me. Thank you.

Great, thanks for testing!

**Comment by Skeb1ns** [comment]
In addition to the issues above I'm now facing a permissions denied issue for standard users when invoking the cmdlet via Intune using ServiceUI. I see that the the cmdlet puts the required stuff in the C:\Windows\TEMP folder but a standard user doesn't have access to that folder.

The scheduled task gets executed and ends with a exit code 0 but that's because wscript doesn't return an error.

**Comment by That-Annoying-Guy** [comment]
@Skeb1ns, you can try this:
-Edit AppDeployToolkitConfig.xml
-Locate:   `<Toolkit_TempPath>$envTemp</Toolkit_TempPath>`
When you run as SYSTEM, $envTemp= C:\Windows\TEMP
-Change it to something like: `<Toolkit_TempPath>$envProgramFiles\PSADT_TEMP</Toolkit_TempPath>`

-Edit Deploy-Application.ps1
-In the PRE-INSTALLATION section create that new folder with: 
`New-Folder "$envProgramFiles\PSADT_TEMP"`

**Why there?** 
-Admins and SYSTEM have full rights to **C:\Program Files\\**
-Users only have Read rights to **C:\Program Files\\** but can run scripts and applications from there.
-If you use Windows' AppLocker, by default you have to whitelist **C:\Program Files\\** to allow applications and scripts to run in it's sub-folders.

**Comment by Skeb1ns** [comment]
> @Skeb1ns, you can try this: -Edit AppDeployToolkitConfig.xml -Locate: `<Toolkit_TempPath>$envTemp</Toolkit_TempPath>` When you run as SYSTEM, $envTemp= C:\Windows\TEMP -Change it to something like: `<Toolkit_TempPath>$envProgramFiles\PSADT_TEMP</Toolkit_TempPath>`
> 
> -Edit Deploy-Application.ps1 -In the PRE-INSTALLATION section create that new folder with: `New-Folder "$envProgramFiles\PSADT_TEMP"`
> 
> **Why there?** -Admins and SYSTEM have full rights to **C:\Program Files\** -Users only have Read rights to **C:\Program Files\** but can run scripts and applications from there. -If you use Windows' AppLocker, by default you have to whitelist **C:\Program Files\** to allow applications and scripts to run in it's sub-folders.

Brilliant suggestion! I've modified the .xml to use `C:\Program Files\PSAppDeployToolkit` as the temp folder and added `New-Folder "$envProgramFiles\PSAppDeployToolkit"` to `Deploy.Application.ps1`.

I updated line 10604 by adding 2 single quotes to escape the space in the path `& `"'$executeToastAsUserScript`'` and it worked.

Again: this is to fix the scenario where deployment gets started in the SYSTEM context but ServiceUI is used to bring the session to the end user so that interaction is possible. `Show-BalloonTip` kicks off `Execute-ProcessAsUser` but puts the .vbs script and .ps1 script to the default temp folder C:\Windows\TEMP where a standard user doesn't have access to.

**Comment by seanlillis** [comment]
I think I've found a way around this @Skeb1ns. Execute-ProcessAsUser will now try to save the VBS and PS1 toast notification script in the profile of the target user the function is running against, meaning it will not attempt to use $envTemp or in the case or running as a different user (e.g. admin) it will not save the file in the admin user's profile which the target (standard) user does not have access to. I've tested this in 3 scenarios and all are working:

1. Run as standard user
2. Run as admin (different user)
3. Run as system with user interaction

**Comment by Skeb1ns** [comment]
An even better solution. I thought of something like that as well, but didnt' got the time to dig in the module.

One final issue remains which is irrelevant to the kit itself: Defender ATP doesn't like the Execute-ProcessAsUser cmdlet and marks the actions as a "Suspicious Scheduled Task has been launched" in our monitoring.

Not sure how to deal with that to be honest but I'm currently looking into it.

**Comment by seanlillis** [comment]
> An even better solution. I thought of something like that as well, but didn't got the time to dig in the module.
> 
> One final issue remains which is irrelevant to the kit itself: Defender ATP doesn't like the Execute-ProcessAsUser cmdlet and marks the actions as a "Suspicious Scheduled Task has been launched" in our monitoring.
> 
> Not sure how to deal with that to be honest but I'm currently looking into it.

I saw something similar with a different security product and v3.9.1 where Execute-ProcessAsUser saved a script in a profile that was inaccessible to the user. That issue is resolved with the fix I've added for v3.9.2. Curious if it also resolves the issue with Defender ATP? You can download the latest code from the master branch.

**Comment by Skeb1ns** [comment]
Oh boy, the saga continues: Now AppLocker gets in the way and blocks the .vbs and .ps1 files when running from the user directory. I've added both hashes to the allowlist but since they change depending on the parameters and paths written to both files this isn't an option.

I don't think this is going to work for a tightly controlled environment when deploying apps via Intune since the whole ordeal is the lack of the option to allow user interaction without resorting to ServiceUI (An option which MECM does have).

Or you could build in an function to automatically sign both scripts using a cert and admins could allow the cert in their AppLocker config but that is a stretch.

I think I will just comment out the Show-BalloonTip references for now since the Company Portal also shows balloon tips when starting an install (though less pretty).

**Comment by Gordy-7** [comment]
This still isnt working for me on Win11 OS and I have changed the xml to write to the new program files path. 

Win10 is fine. 

The show-welcome message on win11 as well still looks like the grey win7 version, im assuming this needs to be amended in the .xml?

**Comment by Gordy-7** [comment]
i am finding this rather frustrating as the notifications are not throwing any errors but will still not show on my win11 device.

The icons on my win10 are not showing our company logo plus, the initial welcome screen still looks very windows 7 and not win10 above. 

We may have to either stick with 3.8.4 or find an alternative packaging method. The notifications are crucial for our users.

**Comment by Gordy-7** [comment]
We are still seeing the same behaviour.

No errors and vbs is not blocking either. The installation just runs as if we have selected noninteractive. tried all the hotfixes but, these do nothing to resolve the issue. 

 We are just using v3.8.2 for the time being as that is still showing us the balloon tip notifications which we need for our users. 

We are hoping the a newer/patched version is released soon as this one seems to be very buggy at the moment.
